### ISSUE TITLE
커뮤니티 재난상황 fake api 개발

### ISSUE THREAD

**Issue by nohy6630** [Team-NumberOne/Daepiro_Backend#31]
## todo
- [x] 글 목록 조회 fake api 개발
- [x] 특정 글의 댓글 목록 조회 fake api 개발
- [x] 댓글 수정 fake api 개발
- [x] 댓글 삭제 fake api 개발
